site_name: Automizer.cloud Affiliate API
dev_addr: 127.0.0.1:8001
theme: readthedocs
nav:
    - Home: index.md
    - General Request Information: requests.md
    - Products: products.md
    - Related Entities: relatedentities.md
