site_name: Automizer.cloud Affiliate API
dev_addr: 127.0.0.1:8001
theme: readthedocs
pages:
    - Home: index.md
    - General Request Information: requests.md
    - Campaigns: campaigns.md
    - Products: products.md
    - Available Offers (Marketplace) - Temporarily unavailable: availableoffers.md
    - Campaign Request - Temporarily unavailable: campaignrequest.md
    - Related Entities: relatedentities.md
